export default {
    DUXFORM_SET_FORM_DATA: "DUXFORM_SET_FORM_DATA",
    DUXFORM_SET_FIELD_DATA: "DUXFORM_SET_FIELD_DATA",

    DUXAUTOCOMPLETE_UNITTEST_FORM: "DUXAUTOCOMPLETE_UNITTEST_FORM",
    DUXAUTOCOMPLETE_UNITTEST_FIELD: "DUXAUTOCOMPLETE_UNITTEST_FIELD",
};
